# Generated by Django 4.2.7 on 2023-11-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=150)),
                ('rating', models.FloatField()),
                ('countries', models.CharField(max_length=150)),
                ('poster', models.TextField()),
                ('length', models.IntegerField()),
            ],
        ),
    ]
