# Generated by Django 4.2.7 on 2023-11-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_search', '0002_alter_film_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
