# Generated by Django 4.2.7 on 2023-11-29 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kino_search', '0003_alter_film_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='film',
            unique_together=set(),
        ),
    ]
