# Generated by Django 4.2.7 on 2023-12-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_search', '0005_alter_film_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.TextField(blank=True),
        ),
    ]
