# Generated by Django 4.2.7 on 2023-12-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_search', '0006_alter_film_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='slug',
            field=models.SlugField(default=False),
        ),
    ]
