# Generated by Django 4.2.7 on 2023-12-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino_search', '0007_film_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='length',
        ),
        migrations.AddField(
            model_name='film',
            name='movie_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='film',
            name='series_length',
            field=models.IntegerField(default=0),
        ),
    ]
