# Generated by Django 4.2.7 on 2023-12-26 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kino_search', '0009_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Films_with_Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=150)),
                ('rating', models.FloatField()),
                ('countries', models.CharField(max_length=150)),
                ('poster', models.TextField(blank=True)),
                ('movie_length', models.IntegerField(default=0)),
                ('series_length', models.IntegerField(default=0)),
                ('slug', models.SlugField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kino_search.categories')),
            ],
        ),
    ]
